version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  app:
    image: sumeetrawal1/task-manager-app
    ports:
      - "80:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
