version: '3'

services:
  backend:
    build: .
    ports:
      - "80:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
